version: "3.9"
name: godel

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: godel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-godel}
      POSTGRES_USER: ${POSTGRES_USER:-godel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-godel}
      # Optional: set POSTGRES_INITDB_ARGS in .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - godel_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      - godel_net

volumes:
  godel_pgdata:
    name: godel_pgdata
    driver: local

networks:
  godel_net:
    name: godel_net


