version: "3.9"
name: godel

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-godel_db}
      POSTGRES_USER: ${POSTGRES_USER:-godel_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      # Optional: set POSTGRES_INITDB_ARGS in .env
    ports:
      - "${POSTGRES_PORT:-5444}:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 12

volumes:
  database_data:


